
import "./globals.css";
import i18nConfig from "@/i18nConfig";


export const metadata = {
  title: "Deschide.MD",
  description: "Generated by create next app",
};

export const generateStaticParams = ()=>{
  return i18nConfig.locales.map(locale=>({locale}))
}

export default async function RootLayout(props) {
  const params = await props.params;

  const {
    locale
  } = params;

  const {
    children
  } = props;

  return <html lang={locale} className="h-full bg-gray-100">
    <body className={` h-full`}>
      {children}
    </body>
  </html>
}
